language: c++

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libxerces-c-dev autoconf automake libtool libfox-1.6-dev libgl1-mesa-dev libglu1-mesa-dev libgdal-dev libproj-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install xerces-c fox; fi
script:
  - make -f Makefile.cvs
  - export CPPFLAGS="$CPPFLAGS -I/opt/X11/include -I/usr/local/include"
  - export LDFLAGS="-L/opt/X11/lib -stdlib=libc++"
  - ./configure CXXFLAGS="-stdlib=libc++"
  - make -j
  - make install
  - make examples
  - export SUMO_HOME=`pwd`
  - (cd examples;_PWD=`pwd`;ls | while read i; do if [[ "$i" == "tools" ]]; then continue;fi;EXEC=$i;echo $i;cd $i;find . -type d | while read j;do echo $j;count=(`ls -1 $j/test.* 2>/dev/null | wc -l`);if [ $count != 0 ];then $_PWD/../bin/$EXEC $j/test.*;SUCCESS=$?;if [ $SUCCESS != 0 ]; then echo "An error occured";exit $SUCCESS;fi;fi;done;SUCCESS=$?;if [ $SUCCESS != 0 ]; then exit $SUCCESS ;fi;cd $_PWD;done;SUCCESS=$?;if [ $SUCCESS != 0 ]; then exit $SUCCESS;fi)

