site_name: SUMO Documentation
site_url: https://angelobanse.github.io/sumo-documentation2/
site_favicon: favicon.ico
repo_url: https://github.com/eclipse/sumo/
edit_uri: edit/master/docs/web/docs/
site_description: SUMO Documentation
#google_analytics:
use_directory_urls: false
dev_addr: 127.0.0.1:8000
#docs_dir: docs
#site_dir: site
copyright: "Copyright &copy; 2001 - 2019 German Aerospace Center (DLR) and others."

nav:
  - Home: index.md
  - Documentation: SUMO_User_Documentation.md
  - Downloads: Downloads.md
  - FAQ: FAQ.md
  - Contact: Contact.md
  - ChangeLog: ChangeLog.md
  - Developer: Developer/Main.md
  - Recent Changes: https://github.com/eclipse/sumo/commits/master/docs

theme:
  name: mkdocs
  custom_dir: theme/
  shortcuts:
    help: 191     # ?
    search: 83    # s
    edit: 69      # e

plugins:
  - search
  - git-revision-date
  - macros

extra_css: 
  - extra.css

markdown_extensions:
  - admonition
  - pymdownx.tilde
  - meta
  - pymdownx.keys
  - footnotes
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  #- mdx_math:
      #enable_dollar_delimiter: True
  #  - pymdownx.emoji
  #- pymdownx.arithmatex
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "#"
      separator: "_"
      baselevel: 1
  - pymdownx.magiclink:
      provider: github
  - mdx_gh_links:
      user: eclipse
      repo: sumo

python_module: special_macros

extra:
    Version: 1.3.1
    ReleaseDate: 27.08.2019

    AdditionalFile: '[*additional-file*](SUMO.md#format_of_additional_files)'
    AdditionalFiles: '[*additional-files*](SUMO.md#format_of_additional_files)'
    DT_2DBoundingBox: '[*&lt;2D-BOUNDING_BOX&gt;*](Basics/Notation.md#referenced_data_types)'
    DT_2DPosition: '[*&lt;2D-POSITION&gt;*](Basics/Notation.md#referenced_data_types)'
    DT_BOOL: '[*&lt;BOOL&gt;*](Basics/Notation.md#referenced_data_types)'
    DT_Color: '[*&lt;COLOR&gt;*](Basics/Notation.md#referenced_data_types)'
    DT_FILE: '[*&lt;FILE&gt;*](Basics/Notation.md#referenced_data_types)'
    DT_FLOAT: '[*&lt;FLOAT&gt;*](Basics/Notation.md#referenced_data_types)'
    DT_IDList: '[*&lt;ID&gt;*](Basics/Notation.md#referenced_data_types)'
    DT_INT: '[*&lt;INT&gt;*](Basics/Notation.md#referenced_data_types)'
    DT_NET: '[*&lt;NETWORK_FILE&gt;*](Basics/Notation.md#referenced_data_types)'
    DT_Routes: '[*&lt;ROUTES_FILE&gt;*](Basics/Notation.md#referenced_data_types)'
    DT_STR: '[*&lt;STRING&gt;*](Basics/Notation.md#referenced_data_types)'
    DT_TIME: '[*&lt;TIME&gt;*](Basics/Notation.md#referenced_data_types)'
    Outdated: '<div style="background: #801010; padding: .5em; border: 1px dashed #ffcc44; margin-right:10px; margin-left:10px; color: #ffffff">This information is outdated.</div>'
    Source: 'https://github.com/eclipse/sumo/blob/master/'
    SUMO: '***&lt;SUMO_HOME&gt;***'
    SUMOUSERConference: '[SUMO User Conference](https://www.dlr.de/ts/en/desktopdefault.aspx/tabid-3930/20125_read-47741)'