name: C/C++ CI

on: [push]


jobs:
  
  ###########################
  # BUILDING ON WINDOWS
  ###########################
  build-windows:
    runs-on: windows-latest
    steps:
    
    - name: Checkout SUMO
      uses: actions/checkout@v2
      with:
        path: SUMO 
      
    - name: Checkout SUMO Libraries
      uses: actions/checkout@v2
      with:
        repository: DLR-TS/SUMOLibraries 
        path: SUMOLibraries
    
    - name: Checkout SUMO Libraries Submodules
      run: |
        cd SUMOLibraries
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1

    - name: Setup Python 
      uses: actions/setup-python@v1
      with:
        python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    
    - name: Install python wheel
      run: python -m pip install wheel
   
    - name: Building SUMO
      env:
        # Allow CMake build to use multiple processors (4)
        CMAKE_BUILD_PARALLEL_LEVEL: 4
      run: |
        cd SUMO
        mkdir build_msvc
        cd build_msvc
        cmake .. -G"Visual Studio 16 2019" -A x64
        cmake --build . --config Release
        cd ..
        python tools\build\setup-libsumo.py bdist_wheel
 
  ###########################
  # BUILDING ON LINUX
  ###########################
  build-linux:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
   
    - name: prepare-system
      run: sudo apt-get update && sudo apt-get install cmake libeigen3-dev libxerces-c-dev libfox-1.6-dev libgdal-dev libproj-dev libgtest-dev libgl2ps-dev python3-dev swig openjdk-8-jdk maven
    
    - name: prepare-gtest
      run: pushd /usr/src/gtest; sudo mkdir build; cd build; sudo cmake ..; sudo make; sudo cp libgtest* /usr/lib/;
    
    - name: build-sumo
      run: mkdir cmake-build && cd cmake-build && cmake .. && make -j4

    - name: build-traas
      run: cd cmake-build && make traas
      
    - name: make-install
      run: cd cmake-build && sudo make install
      
    - name: make-examples-and-test
      run: cd cmake-build && make CTEST_OUTPUT_ON_FAILURE=1 examples test
